version: "3.9"
services:
  db:
    image: postgres:14-alpine3.20
    container_name: spring_magic_postegres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: spring_magic
      POSTGRES_DB: spring_magic
      POSTGRES_PASSWORD: 12345
      REDIS_HOST: cache_magic
      REDIS_PORT: 6379

  redis:
    container_name: cache_magic
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  rabbitmq:
    image: "rabbitmq:3.8.6-management-alpine"
    container_name: rabbitmq-magic
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  cache:
    driver: local