version: "3.9"
services:
  springboot-app:
    image: magic_img
    restart: always
    build: .
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      PROFILE: stressTest
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    container_name: cache_magic
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  rabbitmq:
    image: "rabbitmq:3.8.6-management-alpine"
    container_name: rabbitmq-magic
    ports:
      - 5672:5672
      - 15672:15672

volumes:
    cache:
      driver: local