spring:
  application:
    name: magic
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  liquibase:
    change-log: classpath:db/migration/changelog-master.xml
    enabled: true
    contexts: dev
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 500
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  datasource:
    url: jdbc:postgresql://${POSTG_HOST:localhost}:${POSTG_PORT:5432}/spring_magic
    username: ${POSTG_USER:spring_magic}
    password: ${POSTG_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 95
    cache:
      type: redis

api:
  security:
    token: ${JWT_SECRET:teste12345}
  utils:
    totalPage: ${TOTAL_PAGE:937}
    cacheDuration: ${CACHE_DURATION:30}