spring:
  application:
    name: magic
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  liquibase:
    change-log: classpath:db/migration/changelog-master.xml
    enabled: true
    contexts: stressTest
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 500
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 95
    cache:
      type: redis

api:
  security:
    token: ${JWT_SECRET:teste12345}
  utils:
    totalPage: ${TOTAL_PAGE:937}