spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
  liquibase:
    change-log: classpath:db/migration/changelog-master.xml
    enabled: true
    contexts: test
  application:
    name: teste_test


api:
  security:
    token: ${JWT_SECRET:teste12345}
  utils:
    totalPage: ${TOTAL_PAGE:937}
    cacheDuration: ${CACHE_DURATION:30}