spring:
  application:
    name: magic
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  liquibase:
    change-log: classpath:db/migration/changelog-master.xml
    enabled: true
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_magic
    username: spring_magic
    password: 12345
    driver-class-name: org.postgresql.Driver
